// Code generated by Kitex v0.6.2. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	usermodel "github.com/jun-chiang/go-framework-practice/kitex-service/kitex_gen/usermodel"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SignIn(ctx context.Context, user *usermodel.User, callOptions ...callopt.Option) (r bool, err error)
	SignUp(ctx context.Context, user *usermodel.User, callOptions ...callopt.Option) (r bool, err error)
	GetUserList(ctx context.Context, callOptions ...callopt.Option) (r []*usermodel.User, err error)
	GetUserById(ctx context.Context, id int64, callOptions ...callopt.Option) (r *usermodel.User, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) SignIn(ctx context.Context, user *usermodel.User, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SignIn(ctx, user)
}

func (p *kUserServiceClient) SignUp(ctx context.Context, user *usermodel.User, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SignUp(ctx, user)
}

func (p *kUserServiceClient) GetUserList(ctx context.Context, callOptions ...callopt.Option) (r []*usermodel.User, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserList(ctx)
}

func (p *kUserServiceClient) GetUserById(ctx context.Context, id int64, callOptions ...callopt.Option) (r *usermodel.User, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserById(ctx, id)
}
